; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-basic]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip

board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<basic.cpp>
    
monitor_speed = 115200

[env:esp32-s3-realtime]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip

board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_realtime.cpp>
    
monitor_speed = 115200


[env:esp32-s3-realtime-periodic]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip

board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<real-time-periodic.cpp>
    
monitor_speed = 115200


[env:esp32-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip

board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main.cpp>

[env:esp32-s3-float]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip

board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main-float.cpp>
    
monitor_speed = 115200

[env:esp8266-basic]
platform = espressif8266
board = d1_mini_pro
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<basic.cpp>

monitor_speed = 115200


[env:esp8266_flash_single]
platform = espressif8266
board = d1_mini_pro
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_single_neuron.cpp>

monitor_speed = 115200


[env:esp8266_flash-one-connection]
platform = espressif8266
board = d1_mini_pro
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_one_connection.cpp>

monitor_speed = 115200


[env:esp8266_flash-full]
platform = espressif8266
board = d1_mini_pro
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_full.cpp>

monitor_speed = 115200


[env:esp8266_flash-empty]
platform = espressif8266
board = d1_mini_pro
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_empty.cpp>

monitor_speed = 115200


[env:esp32-s3-flash-single]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_single_neuron.cpp>

monitor_speed = 115200


[env:esp32-s3-flash-empty]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_empty.cpp>

monitor_speed = 115200


[env:esp32-s3-flash-full]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_full.cpp>

monitor_speed = 115200


[env:esp32-s3-flash-one-connection]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = arduino

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++20
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

build_src_filter =
    -<*>
    +<main_flash_one_connection.cpp>

monitor_speed = 115200